FROM python:3.10.10-slim

RUN pip install --upgrade pip
RUN pip install \
    dagster \
    dagster-graphql \
    dagit \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY ./dagster.yaml ./app/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME