version: '3'
services:
  dagster-dagit:
    build: .
    networks:
      - dagster_net
    ports:
      - 3000:3000
  dagster-daemon:
    build: .
    networks:
      - dagster_net
    command: "dagster-daemon run"
  dagster-postgres:
    image: postgres:13.3
    networks:
      - dagster_net
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_db:/var/lib/postgresql/data 
networks:
  dagster_net:
    driver: bridge
    
#https://github.com/AntonFriberg/dagster-project-example
#https://docs.dagster.io/deployment/guides/docker

